---
- name: Install and configure NGINX with HTTPS
  hosts: all
  become: true

  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: present
      update_cache: yes

  - name: Copy SSL Certificate
    copy:
      src: ssl/selfsigned.crt
      dest: /etc/ssl/certs/selfsigned.crt
      owner: root
      group: root
      mode: '0644'

  - name: Copy SSL Key
    copy:
      src: ssl/selfsigned.key
      dest: /etc/ssl/private/selfsigned.key
      owner: root
      group: root
      mode: '0600'

  - name: Upload custom NGINX config
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-available/default

  - name: Restart NGINX
    service:
      name: nginx
      state: restarted
